### ISSUE TITLE
Add assembleStorage and disassembleStorage methods for DEN

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f23-SpMV#34]
## Description: 
Add assemble storage and disassemble storage functions to the Dense matrix class

## Tasks:
- [ ] Write an assemble function
    - Inputs are number of rows and number of columns
    - Allocates an array A that is nrows x ncols
- [ ] Write a disassemble function
    - Input is the dense matrix A
    - Deletes A

## Definition of done:
This task is done when it passes the unit test which will test whether the storage has been created or destroyed.

**Comment by sthvkbht** [comment]
Tasks are well defined and on point for the issue being addressed. 👍

**Comment by sthvkbht** [comment]
Implementation compiles and seems to carry out the described tasks.
